/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/sofa-chair.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import SofaChair from "../public/models/sofa-chair.glb";

export function Model(props) {
  const { nodes, materials } = useGLTF(SofaChair);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane_012.geometry}
        material={materials._sofa_chair_wire_204204204}
        position={[0.065, 0, 0.048]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Plane_013.geometry}
        material={materials._sofa_chair_wire_204204204}
        position={[0.065, 0, 0.048]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Plane_006.geometry}
        material={materials._sofa_chair_wire_204204204}
        position={[0.065, 0, 0.048]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload(SofaChair);
